### ISSUE TITLE
[study] Create Manpages from README.md

### ISSUE THREAD

**Issue by dj4ngo** [openuado/niet#22]

**Comment by 4383** [comment]
this issue can be completed in similar way that #23 by using sphinx and by provided dedicated configuration for man page

- [Sphinx documentation for manpages](http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output)
- [example of using sphinx for manpages](https://stackoverflow.com/questions/7176560/generating-python-cli-man-page)

**Comment by 4383** [comment]
Also if we provide manpages and packages like RPM, etc... (#16, #17, #18) we can provide one package dedicated to the executable and one package dedicated to the manpage.

Example:
```shell
$ yum install niet
$ yum install niet-man
```
@dj4ngo what do you think about this?

**Comment by 4383** [comment]
Ressources for packaging manpages in python (niet distribued via pip):
- https://github.com/pypa/packaging-problems/issues/72

**Comment by 4383** [comment]
https://github.com/pypa/pipenv/issues/444
