### ISSUE TITLE
add raw output format

### ISSUE THREAD

**Issue by aslafy-z** [openuado/niet#45]
As `jq` provides a `--raw` switch, niet could provide a raw output format that allows getting the value without any clutter (double quotes).

**Comment by 4383** [comment]
Hey

If I understood it correctly you don't want to get simple or double quotes in outputs, it's right?

This is the default behaviours with niet:
```shell
echo '{"key": "value"}' | niet key          
value
```

If you want simple or double quotes you need to use the `format` parameter, so we don't need a `--raw` option here.

Thoughs?

**Comment by aslafy-z** [comment]
Thank you for your prompt answer, it looks that this bug is specific to python 2.7. See #46

**Comment by 4383** [comment]
> Thank you for your prompt answer, it looks that this bug is specific to python 2.7. See #46

See my response there #46

**Comment by dj4ngo** [comment]
I think we could close this issue since it is the default comportment, we should work on the #46 if it is still happening...

**Comment by 4383** [comment]
Since the comments above.
