### ISSUE TITLE
Escaping dashes

### ISSUE THREAD

**Issue by NEOhidra** [openuado/niet#49]
Is it possible to escape a dash in key names?

Using niet version 1.5.1 and python Python 3.7.3 the presence of dash in a key leads to:

> jmespath.exceptions.LexerError: Bad jmespath expression: Unknown token '-':

Example:
`echo '{"key-test": "value"}' | niet key-test`

**Comment by 4383** [comment]
Hello @NEOhidra,

Thanks to reporting this issue.
I already seen this issue, I need to take a look deeper to figure out if it can be fixed through `jmespath` or directly on `niet`.

Feel free to propose a patch if you already have a solution.

**Comment by 4383** [comment]
So, `jmespath` is designed like this, is not a bug it's a feature ;)

Hence, you can fix your issue by surrounding your expression with simple and double quotes, like this:
```
echo '{"foo-biz": "bar", "fizz": {"buzz": ["zero", "one", "two", "three"]}}' | niet -f dquote '"foo-biz"'
echo '{"key-test": "value"}' | niet '"key-test"'
```
- https://github.com/jmespath/jmespath.py/issues/109#issuecomment-240315651
- http://jmespath.org/specification.html#identifiers
- https://github.com/jmespath/jmespath.py/issues/109
- http://jmespath.org/specification.html#examples

**Comment by 4383** [comment]
I'll update the documentation to refer how to use properly keys with dash.

**Comment by NEOhidra** [comment]
I see, thank you!

**Comment by 4383** [comment]
@NEOhidra feel free to put some reviews there:
- https://github.com/openuado/niet/pull/50

**Comment by 4383** [comment]
Now fixed by commit https://github.com/openuado/niet/commit/516f4fe8d985dd436100ad56a0b2fbec9f87f1fc in version 1.6.0
- https://github.com/openuado/niet/commit/516f4fe8d985dd436100ad56a0b2fbec9f87f1fc
- https://pypi.org/project/niet/1.6.0/
- https://github.com/openuado/niet/releases/tag/1.6.0

Upgrade to the latest version by using:
```sh
$ pip install -U niet
```

You can verify it by executing:
```sh
$ echo '{"key-test": "value"}' | niet '"key-test"'
value
$ echo '{"key-test": "value"}' | niet key-test
value
```

**Comment by NEOhidra** [comment]
Hervé - you are great!
This is more like a feature, at least to me.

Thank you!
