### ISSUE TITLE
Standardize CLI arguments for new incoming features

### ISSUE THREAD

**Issue by dj4ngo** [openuado/niet#60]
We must standardize the CLI since several features are coming and they will have a impact ons args.

REMIDER :
```
$ niet --help
usage: niet [-h] [-f {json,yaml,eval,newline,ifs,squote,dquote}] [-s] [-v]
            object [file]

Read data from YAML or JSON file

positional arguments:
  object                Path to object separated by dot (.). Use '.' to get
                        whole file. eg: a.b.c
  file                  Optional JSON or YAML filename. If not provided niet
                        read from stdin

optional arguments:
  -h, --help            show this help message and exit
  -f {json,yaml,eval,newline,ifs,squote,dquote}, --format {json,yaml,eval,newline,ifs,squote,dquote}
                        output format
  -i, --in-place        Perform modification in place. Will so alter read file
  -o OUTPUT_FILE, --output OUTPUT_FILE
                        Print output in a file instead of stdout (surcharged
                        by infile parameter if set)
  -s, --silent          silent mode, doesn't display message when element was
                        not found
  -v, --version         print the Niet version number and exit (also
                        --version)
```

**Comment by dj4ngo** [comment]
Incoming features are the add command and deletion ones
Standard usage : 
`niet .object file.yaml` = Return object from file
`echo 'toto' | niet .` = Return object from stdin; no need of second positional arg since reading from stdin

Deletion : 
Several ways of work identified: 
Solution 1 `niet -d .objects.object1 --del .objects.object2 file.yml` => The is no need for .object first positional arg in this case, this will remove only these two objects from file. The -i can be used to makes the change in the file itself (or -o for writing in an other ourput file)
Solution 2  `niet .objects file.yaml --del object1 object2` => Delete object1 and object2 from objects and return all the file.yaml except these two objects. 
Solution 3 `niet .objects file.yaml --del object1 -d object2` => Extract the .objects object from file.yaml and return it with deleting object1 and object2. Difference with previous one is that the output is only on .objects object and there is nothing outside of .objects.

**Comment by 4383** [comment]
IMHO the second solution make no sense.

Until now the object to handle, if exist, was the returned part (the output), so if we consider it we still need to return only the section who correspond to this object. For this reason I'm not confortable with the second solution, I think it could misleading users.

Concerning the first solution, it suppose to move the `object` parameter as an optional parameter... I'm not a big fan... This will break the standard usage of niet where the `object` is the central piece of this software and of the niet logic.

So the third solution appear to me as the right solution and the more flexible one!

With this one we can delete from everywhere and the `object` parameter will determine the scope of the deletion.

Example:
```
$ echo '{"one": 1, "two": 2, "three": 3, "four": {"five": 5, "six": 6, "seven": 7}}' | niet  . -d .four.five .four.seven -f json
{"one": 1, "two": 2, "three": 3, "four": {"six": 6}}
$ echo '{"one": 1, "two": 2, "three": 3, "four": {"five": 5, "six": 6, "seven": 7}}' | niet  .four -d six -f json
{"four": {"five": 5, "seven": 7}}
$ # in the following example `six` is outside of the scope of the `two` key so deletion will be ignored
$ # how is it useful to return an error code in this situation? 
$ echo '{"one": 1, "two": 2, "three": 3, "four": {"five": 5, "six": 6, "seven": 7}}' | niet  .two -d six -f json
{"two": 2}
$ echo $?
0
```

**Comment by dj4ngo** [comment]
I am not so comfortable with the nargs feature to have several objets after the -d or --del argument indeed. 

But What we could do is to allow to have some multiples arguments in one arg, I mean this kind of thing : 

```bash
$echo '{"one": 1, "two": 2, "three": 3, "four": {"five": 5, "six": 6, "seven": 7}}' | \
> niet  . -d 'one .four.six' -f json
{"two": 2, "three": 3, "four": {"five": 5, "seven": 7}}
```
This can easily be obtained by intelligency spliting the only arg in a list separated by spaces (with taking care about quotes and backslash).
This allow to deal with bash table (if there is no spaces in the bash table), and still fix to one argument so there can be no issue regarding if you plain to use it before the positionning argument or after.
