### ISSUE TITLE
sub-element with dashes is not found

### ISSUE THREAD

**Issue by rez-** [openuado/niet#66]
The following sub element can not be found:

```
env:
  sub-elem: value
```

To quickly test it:
`echo -e "env:\n  sub-elem: value" | niet 'env.sub-elem'`

**Comment by 4383** [comment]
Hello,

First thanks for reporting this bug!

Indeed I can easily reproduce the issue, thanks for the given details.

I'll investigate more deeply to try to fix it.

If you already have some clues don't hesitate to propose a patch by submitting a pull request. We will be happy to review your changes.

Thanks

**Comment by 4383** [comment]
After further investigation I found that you can fix your issue by using the following syntaxe:

```yaml
# test.yaml
env:
    elem-sub: value
```

```sh
$ niet env.'"elem-sub"' test.yaml     
```

However I wonder if you can pass YAML format by using `echo` as you proposed in your previous example.

Locally the YAML parser doesn't recognize it as a valid YAML input.

Please take a look to the examples provided in our [README.md](https://github.com/openuado/niet).

I hope these info will help you, please confirm that it fix your issue and then feel free to close this bug if it's ok for you.

Thanks,

**Comment by 4383** [comment]
@rez- any update?

**Comment by rez-** [comment]
Thanks, you are right, i did not know the syntax!
