### ISSUE TITLE
pyyaml 5.1 vulnerabilities

### ISSUE THREAD

**Issue by henryykt** [openuado/niet#68]
Thanks for this tool!

Would it be possible to upgrade to use pyyaml to >= 5.4? According to https://snyk.io/vuln/pip:pyyaml, there are several vulnerabilities in 5.1.

Thanks,

Henry

**Comment by 4383** [comment]
Hello Henry,

I'll have a look asap to see if an upgrade is possible, else, feel free to
propose a pull requests to bump the version of pyyaml.

Hervé

Le jeu. 22 avr. 2021 à 3:33 AM, Henry Tang ***@***.***> a
écrit :

**Comment by 4383** [comment]
Fixed by eac5518
